version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=olio
      - POSTGRES_PASSWORD=olio
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    command: sh -c "bundle && bundle exec puma config.ru -C config/puma.rb -p 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      - RACK_ENV=production
    depends_on:
      - postgres
    profiles:
      - app
volumes:
  postgres-data:
