default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: olio
  password: olio
  port: 5432
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: olio_development

test:
  <<: *default
  database: olio_test
